// Generated by CoffeeScript 1.6.3
var Sweatshop, parseArgs, _,
  __slice = [].slice;

_ = require('lodash');

parseArgs = function(args) {
  var attrs, callback, name;
  if (typeof _(args).first() === 'string') {
    name = args.shift();
  }
  switch (args.length) {
    case 1:
      callback = args[0];
      break;
    case 2:
      attrs = args[0], callback = args[1];
  }
  return {
    name: name,
    attrs: attrs,
    callback: callback
  };
};

Sweatshop = (function() {
  function Sweatshop() {
    var args, _ref;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    if (typeof _(args).last() === 'object') {
      this.parent = args.pop();
    }
    this.factoryFn = args.pop();
    this.model = (_ref = args.pop()) != null ? _ref : Object;
    this.children = [];
  }

  Sweatshop.prototype.json = function() {
    var args, attrs, callback, name, _ref,
      _this = this;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    _ref = parseArgs(args), name = _ref.name, attrs = _ref.attrs, callback = _ref.callback;
    if (name != null) {
      return this.get(name).json(attrs, callback);
    }
    attrs = _.clone(attrs != null ? attrs : {});
    return this.factoryFn.call(attrs, function(err) {
      if (err != null) {
        return callback(err);
      }
      return _this.parent.factoryFn.call(attrs, function(err) {
        var result;
        if (err != null) {
          return callback(err);
        }
        result = _.merge({}, attrs);
        return callback(null, result);
      });
    });
  };

  Sweatshop.prototype.build = function() {
    var args, attrs, callback, name, _ref,
      _this = this;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    _ref = parseArgs(args), name = _ref.name, attrs = _ref.attrs, callback = _ref.callback;
    if (name != null) {
      return this.get(name).build(attrs, callback);
    }
    return this.json(attrs, function(err, result) {
      var model;
      if (err != null) {
        return callback(err);
      }
      model = _this.modelInstanceWith(result);
      return callback(null, model);
    });
  };

  Sweatshop.prototype.create = function() {
    var args, attrs, callback, name, _ref,
      _this = this;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    _ref = parseArgs(args), name = _ref.name, attrs = _ref.attrs, callback = _ref.callback;
    if (name != null) {
      return this.get(name).create(attrs, callback);
    }
    return this.build(attrs, function(err, model) {
      if (err != null) {
        return callback(err);
      }
      return _this.saveModel(model, callback);
    });
  };

  Sweatshop.prototype.define = function() {
    var args, name;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    name = typeof _(args).first() === 'string' ? args.shift() : this.children.length;
    return this.children[name] = (function(func, args, ctor) {
      ctor.prototype = func.prototype;
      var child = new ctor, result = func.apply(child, args);
      return Object(result) === result ? result : child;
    })(Sweatshop, __slice.call(args).concat([this]), function(){});
  };

  Sweatshop.prototype.get = function(name) {
    return this.children[name] || (function() {
      throw "Unknown factory `" + name + "`";
    })();
  };

  Sweatshop.prototype.modelInstanceWith = function(attrs) {
    return new this.model(attrs);
  };

  Sweatshop.prototype.saveModel = function(model, callback) {
    if (_.isFunction(model.save)) {
      return model.save(callback);
    } else {
      return callback(null, model);
    }
  };

  return Sweatshop;

})();

module.exports = new Sweatshop(_.defer);
