# • ▌ ▄ ·.       ▄▄▄  ▄▄▄ .    ·▄▄▄▄▄▄ . ▄▄▄· ▄▄▄▄▄▄• ▄▌▄▄▄  ▄▄▄ ..▄▄ ·
# ·██ ▐███▪▪     ▀▄ █·▀▄.▀·    ▐▄▄·▀▄.▀·▐█ ▀█ •██  █▪██▌▀▄ █·▀▄.▀·▐█ ▀.
# ▐█ ▌▐▌▐█· ▄█▀▄ ▐▀▀▄ ▐▀▀▪▄    ██▪ ▐▀▀▪▄▄█▀▀█  ▐█.▪█▌▐█▌▐▀▀▄ ▐▀▀▪▄▄▀▀▀█▄
# ██ ██▌▐█▌▐█▌.▐▌▐█•█▌▐█▄▄▌    ██▌.▐█▄▄▌▐█ ▪▐▌ ▐█▌·▐█▄█▌▐█•█▌▐█▄▄▌▐█▄▪▐█
# ▀▀  █▪▀▀▀ ▀█▄▀▪.▀  ▀ ▀▀▀     ▀▀▀  ▀▀▀  ▀  ▀  ▀▀▀  ▀▀▀ .▀  ▀ ▀▀▀  ▀▀▀▀
#
# - Support for promises
# - Autogenerated factories from Mongoose models
#     - Soon: support for <<json-schema>> as well

hatch = require 'chicken-hatchling'
hatch 4000, -> console.log "Thank you!"
