// Generated by CoffeeScript 1.7.1
var dotpath, getPathArray, getPointer;

getPointer = function(object, pathArray, init) {
  var component, pointer, _i, _len;
  if (init == null) {
    init = false;
  }
  pointer = object;
  for (_i = 0, _len = pathArray.length; _i < _len; _i++) {
    component = pathArray[_i];
    if (init && typeof pointer[component] !== 'object') {
      pointer[component] = {};
    }
    pointer = pointer[component];
  }
  return pointer;
};

getPathArray = function(pathString) {
  return pathString.split('.');
};

module.exports = dotpath = {
  get: function(object, pathString) {
    return getPointer(object, getPathArray(pathString));
  },
  set: function(object, pathString, value, init) {
    var end, pathArray, pointer;
    if (init == null) {
      init = true;
    }
    pathArray = getPathArray(pathString);
    end = pathArray.pop();
    pointer = getPointer(object, pathArray, init);
    return pointer[end] = value;
  },
  clear: function(object, pathString) {
    return delete dotpath.get(object, pathString);
  },
  subpaths: function(pathString) {
    var component, rebuildPath, subPaths, _i, _len, _ref;
    rebuildPath = [];
    subPaths = [];
    _ref = getPathArray(pathString);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      component = _ref[_i];
      rebuildPath.push(component);
      subPaths.push(rebuildPath.join('.'));
    }
    return subPaths;
  }
};
