// Generated by CoffeeScript 1.7.1
var FactoryDefinition, dotpath,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

dotpath = require('./dotpath');

module.exports = FactoryDefinition = (function() {
  function FactoryDefinition(attrs, mode, args) {
    this.attrs = attrs != null ? attrs : {};
    this.mode = mode;
    this.args = args;
    this._out = {};
    this.attrKeys = Object.keys(this.attrs);
    this.setAttrs();
  }

  FactoryDefinition.prototype.setAttrs = function() {
    var key, value, _ref, _results;
    _ref = this.attrs;
    _results = [];
    for (key in _ref) {
      value = _ref[key];
      if (value !== void 0) {
        _results.push(dotpath.set(this._out, key, value));
      }
    }
    return _results;
  };

  FactoryDefinition.prototype.set = function(key, value, options) {
    var subpath, _i, _len, _ref;
    if (options == null) {
      options = {};
    }
    if (options.init == null) {
      options.init = true;
    }
    _ref = dotpath.subpaths(key);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      subpath = _ref[_i];
      if (__indexOf.call(this.attrKeys, subpath) >= 0) {
        return this.attrs[subpath];
      }
    }
    dotpath.set(this._out, key, value, options.init);
    return value;
  };

  FactoryDefinition.prototype.unset = function(key) {
    return dotpath.clear(this._out, key);
  };

  FactoryDefinition.prototype.embed = function(key, factory, callback) {
    return factory[this.mode](this.get(key), (function(_this) {
      return function(err, value) {
        if (err != null) {
          return callback(err);
        }
        _this.set(key, value);
        return callback(null, value);
      };
    })(this));
  };

  FactoryDefinition.prototype.embedArray = function(key, defaultCount, factory, callback) {
    return callback();
  };

  FactoryDefinition.prototype.get = function(key) {
    return dotpath.get(this._out, key);
  };

  FactoryDefinition.prototype.resolve = function() {
    return this._out;
  };

  return FactoryDefinition;

})();
