// Generated by CoffeeScript 1.7.1
var _,
  __slice = [].slice;

module.exports = _ = {
  last: function(array) {
    return array[array.length - 1];
  },
  isFunction: function(value) {
    return typeof value === 'function';
  },
  defer: function() {
    var args, func;
    func = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    if (!_.isFunction(func)) {
      throw new TypeError;
    }
    return setTimeout((function() {
      return func.apply(void 0, args);
    }), 1);
  }
};
